<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KeywordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('keywords')->insert([
            // Telkomsel (no = 1)
            [
                'merchant_key' => 1,
                'nama_produk' => 'Paket Data 10GB 30 Hari',
                'redeem' => 75000,
                'diskon' => null,
                'skb' => 'Khusus pelanggan Telkomsel, kuota nasional, masa aktif 30 hari.',
                'start_date' => '2025-01-01',
                'end_date' => '2025-12-31',
                'image' => 'storage/promo/promo-telkomsel.jpg',
                'cta_link' => 'https://example.com/telkomsel-10gb',
                'stok' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merchant_key' => 1,
                'nama_produk' => 'Paket Combo 5GB + 100 Menit',
                'redeem' => 50000,
                'diskon' => null,
                'skb' => 'Tidak berlaku kelipatan, hanya untuk pembelian via PaysQift.',
                'start_date' => '2025-02-01',
                'end_date' => '2025-08-31',
                'image' => 'storage/promo/promo-telkomsel.jpg',
                'cta_link' => 'https://example.com/telkomsel-combo',
                'stok' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Toko Makmur Abadi (no = 2) - Shop / Fashion
            [
                'merchant_key' => 2,
                'nama_produk' => 'Kaos Premium Polos',
                'redeem' => 30000,
                'diskon' => 10,
                'skb' => 'Minimal pembelanjaan Rp 150.000, potongan langsung di kasir.',
                'start_date' => '2025-02-01',
                'end_date' => '2025-10-01',
                'image' => 'storage/promo/promo-default.jpg',
                'cta_link' => 'https://example.com/makmur-kaos',
                'stok' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merchant_key' => 2,
                'nama_produk' => 'Voucher Belanja Fashion Rp 50.000',
                'redeem' => 50000,
                'diskon' => null,
                'skb' => 'Berlaku untuk kategori fashion, tidak termasuk produk promo.',
                'start_date' => '2025-03-01',
                'end_date' => '2025-11-30',
                'image' => 'storage/promo/promo-default.jpg',
                'cta_link' => 'https://example.com/makmur-voucher50',
                'stok' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Restoran Ayam Pedas (no = 3) - Food lokal
            [
                'merchant_key' => 3,
                'nama_produk' => 'Paket Hemat Ayam Goreng Pedas',
                'redeem' => 40000,
                'diskon' => 20,
                'skb' => 'Berlaku dine-in dan take away, tidak berlaku delivery.',
                'start_date' => '2025-01-15',
                'end_date' => '2025-09-30',
                'image' => 'storage/promo/promo-default.jpg',
                'cta_link' => 'https://example.com/ayam-pedas-hemat',
                'stok' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Wingstop (no = 4) - Food
            [
                'merchant_key' => 4,
                'nama_produk' => 'Diskon 15% Paket Wings',
                'redeem' => 50000,
                'diskon' => 15,
                'skb' => 'Berlaku di outlet Wingstop tertentu, cek detail di aplikasi.',
                'start_date' => '2025-01-01',
                'end_date' => '2025-06-30',
                'image' => 'storage/promo/promo-wingstop.jpg',
                'cta_link' => 'https://example.com/wingstop-15',
                'stok' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merchant_key' => 4,
                'nama_produk' => 'Voucher Makan Wingstop Rp 75.000',
                'redeem' => 75000,
                'diskon' => null,
                'skb' => 'Tidak dapat digabung dengan promo lain.',
                'start_date' => '2025-03-01',
                'end_date' => '2025-12-31',
                'image' => 'storage/promo/promo-wingstop.jpg',
                'cta_link' => 'https://example.com/wingstop-voucher75',
                'stok' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Pizza Hut (no = 5) - Food
            [
                'merchant_key' => 5,
                'nama_produk' => 'Diskon Rp 100.000 Paket Keluarga',
                'redeem' => 100000,
                'diskon' => null,
                'skb' => 'Minimal pembelian Rp 300.000, khusus dine-in.',
                'start_date' => '2025-01-10',
                'end_date' => '2025-10-10',
                'image' => 'storage/promo/promo-pizzahut.png',
                'cta_link' => 'https://example.com/pizzahut-keluarga',
                'stok' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merchant_key' => 5,
                'nama_produk' => 'Voucher Pizza Hut Rp 50.000',
                'redeem' => 50000,
                'diskon' => null,
                'skb' => 'Bisa digunakan untuk semua menu kecuali alkohol.',
                'start_date' => '2025-04-01',
                'end_date' => '2025-12-31',
                'image' => 'storage/promo/promo-pizzahut.png',
                'cta_link' => 'https://example.com/pizzahut-50k',
                'stok' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // KFC (no = 6) - Food
            [
                'merchant_key' => 6,
                'nama_produk' => 'Paket Super Family Bucket',
                'redeem' => 60000,
                'diskon' => 10,
                'skb' => 'Hanya untuk dine-in, tidak berlaku drive-thru.',
                'start_date' => '2025-02-01',
                'end_date' => '2025-07-31',
                'image' => 'storage/promo/promo-kfc.jpg',
                'cta_link' => 'https://example.com/kfc-family',
                'stok' => 140,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Sociolla (no = 7) - Beauty & Care
            [
                'merchant_key' => 7,
                'nama_produk' => 'Voucher Sociolla Rp 85.000',
                'redeem' => 85000,
                'diskon' => null,
                'skb' => 'Berlaku untuk semua produk kecuali bundle promo.',
                'start_date' => '2025-03-01',
                'end_date' => '2025-09-30',
                'image' => 'storage/promo/promo-sociolla.jpg',
                'cta_link' => 'https://example.com/sociolla-85k',
                'stok' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merchant_key' => 7,
                'nama_produk' => 'Diskon 20% Skincare Pilihan',
                'redeem' => 70000,
                'diskon' => 20,
                'skb' => 'Hanya untuk skincare tertentu, selama persediaan masih ada.',
                'start_date' => '2025-04-01',
                'end_date' => '2025-12-31',
                'image' => 'storage/promo/promo-sociolla.jpg',
                'cta_link' => 'https://example.com/sociolla-skincare20',
                'stok' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Guardian (no = 8) - Beauty & Care
            [
                'merchant_key' => 8,
                'nama_produk' => 'Voucher Guardian Rp 50.000',
                'redeem' => 50000,
                'diskon' => null,
                'skb' => 'Tidak berlaku untuk obat resep dan susu bayi.',
                'start_date' => '2025-02-15',
                'end_date' => '2025-10-31',
                'image' => 'storage/promo/promo-guardian.jpg',
                'cta_link' => 'https://example.com/guardian-50k',
                'stok' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // CGV Cinema (no = 9) - Entertain
            [
                'merchant_key' => 9,
                'nama_produk' => 'Voucher Nonton CGV Rp 50.000',
                'redeem' => 50000,
                'diskon' => null,
                'skb' => 'Berlaku untuk semua film reguler 2D.',
                'start_date' => '2025-06-01',
                'end_date' => '2025-12-31',
                'image' => 'storage/promo/promo-cgv.jpg',
                'cta_link' => 'https://example.com/cgv-50k',
                'stok' => 250,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merchant_key' => 9,
                'nama_produk' => 'Diskon 20% Popcorn & Drink',
                'redeem' => 30000,
                'diskon' => 20,
                'skb' => 'Hanya berlaku bersama tiket film yang sama hari.',
                'start_date' => '2025-05-01',
                'end_date' => '2025-11-30',
                'image' => 'storage/promo/promo-cgv.jpg',
                'cta_link' => 'https://example.com/cgv-popcorn',
                'stok' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Timezone (no = 10) - Entertain
            [
                'merchant_key' => 10,
                'nama_produk' => 'Bonus Saldo Timezone Rp 30.000',
                'redeem' => 30000,
                'diskon' => null,
                'skb' => 'Top-up saldo kartu Timezone, hanya di outlet tertentu.',
                'start_date' => '2025-03-15',
                'end_date' => '2025-09-15',
                'image' => 'storage/promo/promo-default.jpg',
                'cta_link' => 'https://example.com/timezone-30k',
                'stok' => 130,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Traveloka (no = 11) - Vacation
            [
                'merchant_key' => 11,
                'nama_produk' => 'Voucher Hotel Traveloka Rp 80.000',
                'redeem' => 80000,
                'diskon' => null,
                'skb' => 'Minimal transaksi Rp 500.000 untuk hotel domestik.',
                'start_date' => '2025-04-01',
                'end_date' => '2025-10-20',
                'image' => 'storage/promo/promo-traveloka.jpg',
                'cta_link' => 'https://example.com/traveloka-80k',
                'stok' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'merchant_key' => 11,
                'nama_produk' => 'Diskon 10% Tiket Pesawat',
                'redeem' => 90000,
                'diskon' => 10,
                'skb' => 'Maksimal potongan Rp 200.000, rute domestik.',
                'start_date' => '2025-05-01',
                'end_date' => '2025-12-31',
                'image' => 'storage/promo/promo-traveloka.jpg',
                'cta_link' => 'https://example.com/traveloka-flight10',
                'stok' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Indomaret (no = 12) - Shop
            [
                'merchant_key' => 12,
                'nama_produk' => 'Voucher Belanja Indomaret Rp 30.000',
                'redeem' => 30000,
                'diskon' => null,
                'skb' => 'Tidak berlaku untuk pulsa, token listrik, dan pembayaran tagihan.',
                'start_date' => '2025-01-20',
                'end_date' => '2025-09-30',
                'image' => 'storage/promo/promo-default.jpg',
                'cta_link' => 'https://example.com/indomaret-30k',
                'stok' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Alfamart (no = 13) - Shop
            [
                'merchant_key' => 13,
                'nama_produk' => 'Voucher Belanja Alfamart Rp 30.000',
                'redeem' => 30000,
                'diskon' => null,
                'skb' => 'Tidak dapat diuangkan, satu voucher untuk satu transaksi.',
                'start_date' => '2025-02-01',
                'end_date' => '2025-10-31',
                'image' => 'storage/promo/promo-default.jpg',
                'cta_link' => 'https://example.com/alfamart-30k',
                'stok' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
