<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KeywordSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $keywords = [
            // =============== DPS (merchant id 1–5) ===============
            [
                'merchant_key'   => 1,
                'nama_produk'    => 'CLIP N CLIMB BALI',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/clip-n-climb-bali',
                'redeem'         => '100',
                'diskon'         => 'Rp 10.000',
                'skb'            => 'Zone pass di CLIP N CLIMB BALI dengan menukarkan 100 Telkomsel Poin',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/clip-n-climb-bali',
                'stock'          => 100,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 2,
                'nama_produk'    => 'ETERNA AESTHETIC & ANTI AGING CLINIC',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/eterna-laser',
                'redeem'         => '500',
                'diskon'         => '10%',
                'skb'            => 'Diskon 10% untuk treatment LASER by Quanta Skin Rejuvenation',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/eterna-aesthetic',
                'stock'          => 50,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 3,
                'nama_produk'    => 'LABORATORIM PRODIA SINGARAJA BALI',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/prodia-sing',
                'redeem'         => '200',
                'diskon'         => '10%',
                'skb'            => 'Diskon pemeriksaan lab tertentu di Prodia Singaraja',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/prodia-singaraja',
                'stock'          => 30,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 4,
                'nama_produk'    => 'LABORATORIM PRODIA TABANAN BALI',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/prodia-tbn',
                'redeem'         => '200',
                'diskon'         => '10%',
                'skb'            => 'Diskon pemeriksaan lab tertentu di Prodia Tabanan',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/prodia-tabanan',
                'stock'          => 30,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 5,
                'nama_produk'    => 'MIRACLE ULTIMATE DENPASAR',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/miracle',
                'redeem'         => '500',
                'diskon'         => '15%',
                'skb'            => 'Diskon 15% untuk treatment Facial Exosome di Miracle Ultimate Denpasar',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/miracle-ultimate',
                'stock'          => 40,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],

            // =============== KPG (merchant id 6–10) ===============
            [
                'merchant_key'   => 6,
                'nama_produk'    => 'Masterpiece',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/masterpiece',
                'redeem'         => '5000',
                'diskon'         => 'Rp 20.000',
                'skb'            => 'Disc voucher 25rb di Masterpiece Family Karaoke Kupang',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/masterpiece-kpg',
                'stock'          => 20,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 7,
                'nama_produk'    => 'la Moringa',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/la-moringa',
                'redeem'         => '2000',
                'diskon'         => 'Rp 20.000',
                'skb'            => 'Disc 10rb untuk menu makanan di La Moringa Kupang',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/la-moringa',
                'stock'          => 50,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 8,
                'nama_produk'    => 'Nakamura Kupang',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/nakamura',
                'redeem'         => '2000',
                'diskon'         => '10%',
                'skb'            => 'Disc 10% untuk terapi 90m & 120m ruang Executive & VIP',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/nakamura-kpg',
                'stock'          => 40,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 9,
                'nama_produk'    => 'Relaxology Kupang',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/relaxology',
                'redeem'         => '3000',
                'diskon'         => 'Rp 20.000',
                'skb'            => 'Disc treatment 20rb di RX Relaxology Kupang',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/relaxology-kpg',
                'stock'          => 40,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 10,
                'nama_produk'    => 'Dapur Solokoe',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/dapur-solokoe',
                'redeem'         => '2000',
                'diskon'         => 'Rp 20.000',
                'skb'            => 'Disc makanan senilai 5rb di Dapur Solokoe',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/dapur-solokoe',
                'stock'          => 40,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],

            // =============== MTR (merchant id 11–15) ===============
            [
                'merchant_key'   => 11,
                'nama_produk'    => 'JELAJAH COFFEE',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/jelajah-coffee',
                'redeem'         => '1500',
                'diskon'         => 'Rp 20.000',
                'skb'            => 'Voucher minuman di Jelajah Coffee Lombok',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/jelajah-coffee',
                'stock'          => 30,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 12,
                'nama_produk'    => 'B CLINIC',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/b-clinic',
                'redeem'         => '500',
                'diskon'         => '10%',
                'skb'            => 'Diskon 10% untuk treatment kecantikan pilihan di B CLINIC',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/b-clinic',
                'stock'          => 20,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 13,
                'nama_produk'    => 'LOMBOK WILDLIFE PARK',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/lombok-wildlife',
                'redeem'         => '1000',
                'diskon'         => 'Rp 20.000',
                'skb'            => 'Voucher tiket masuk Lombok Wildlife Park',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/lombok-wildlife-park',
                'stock'          => 50,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 14,
                'nama_produk'    => 'DAPUR SAYUR',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/dapur-sayur',
                'redeem'         => '1000',
                'diskon'         => 'Rp 20.000',
                'skb'            => 'Voucher makan di Dapur Sayur',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/dapur-sayur',
                'stock'          => 40,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 15,
                'nama_produk'    => 'SALOME HAIR & BEAUTY',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/salome',
                'redeem'         => '500',
                'diskon'         => '15%',
                'skb'            => 'Diskon 15% untuk treatment salon tertentu di Salome Hair & Beauty',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/salome-hair-beauty',
                'stock'          => 20,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],

            // =============== FLO (merchant id 16–20) ===============
            [
                'merchant_key'   => 16,
                'nama_produk'    => 'KOPI DENG SAPA',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/kopi-deng-sapa',
                'redeem'         => '1500',
                'diskon'         => 'Rp 20.000',
                'skb'            => 'Voucher minuman di Kopi Deng Sapa',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/kopi-deng-sapa',
                'stock'          => 30,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 17,
                'nama_produk'    => 'CAFE HM CAFE & RESTO',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/hm-cafe',
                'redeem'         => '1500',
                'diskon'         => 'Rp 20.000',
                'skb'            => 'Voucher makan/minum di HM Cafe & Resto',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/hm-cafe',
                'stock'          => 40,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 18,
                'nama_produk'    => 'SIBAKLOANG GALLERY COFFE',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/sibakloang',
                'redeem'         => '1500',
                'diskon'         => 'Rp 20.000',
                'skb'            => 'Voucher minuman di Sibakloang Gallery Coffee',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/sibakloang-gallery',
                'stock'          => 30,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 19,
                'nama_produk'    => 'CAFE TERAS LANGIT',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/teras-langit',
                'redeem'         => '1500',
                'diskon'         => 'Rp 20.000',
                'skb'            => 'Voucher minuman di Cafe Teras Langit',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/cafe-teras-langit',
                'stock'          => 30,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'merchant_key'   => 20,
                'nama_produk'    => 'APOTIK TIARA FARM',
                'cta_link'       => 'https://my.telkomsel.com/app/loyalty-reward-detail/tiara-farm',
                'redeem'         => '1000',
                'diskon'         => 'Rp 20.000',
                'skb'            => 'Voucher pembelian obat/produk kesehatan di Apotik Tiara Farm',
                'start_date'     => '2025-01-01',
                'end_date'       => '2025-12-31',
                'link_kv_google' => 'https://drive.google.com/apotik-tiara-farm',
                'stock'          => 50,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
        ];

        DB::table('keywords')->insert($keywords);
    }
}
