<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MerchantSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $merchants = [
            // ================== denpasar ==================
            [
                'nama_merchant'  => 'CLIP N CLIMB BALI',
                'kategori'       => 'liburan',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/clip-n-climb-bali',
                'nama_pic'       => 'Ayu Putu',
                'wa_pic'         => '+6281234567890',
                'daerah'         => 'denpasar',
                'link_gmap'      => 'https://maps.google.com/?q=-8.6705,115.2126',
                'logo_merchant'  => '/storage/logos/clip-n-climb-bali.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'ETERNA AESTHETIC & ANTI AGING CLINIC',
                'kategori'       => 'kecantikan',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/eterna-aesthetic',
                'nama_pic'       => 'Dr. Sari Dewi',
                'wa_pic'         => '+6281234567891',
                'daerah'         => 'denpasar',

                'link_gmap'      => 'https://maps.google.com/?q=-8.6750,115.2180',
                'logo_merchant'  => '/storage/logos/eterna-aesthetic.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'LABORATORIM PRODIA SINGARAJA BALI',
                'kategori'       => 'kecantikan',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/prodia-singaraja',
                'nama_pic'       => 'Made Sari',
                'wa_pic'         => '+6281234567892',
                'daerah'         => 'denpasar',
                'long'           => 115.2200,
                'lat'            => -8.6800,
                'link_gmap'      => 'https://maps.google.com/?q=-8.6800,115.2200',
                'logo_merchant'  => '/storage/logos/prodia-singaraja.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'LABORATORIM PRODIA TABANAN BALI',
                'kategori'       => 'kecantikan',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/prodia-tabanan',
                'nama_pic'       => 'Kadek Wati',
                'wa_pic'         => '+6281234567893',
                'daerah'         => 'denpasar',
                'long'           => 115.2150,
                'lat'            => -8.6850,
                'link_gmap'      => 'https://maps.google.com/?q=-8.6850,115.2150',
                'logo_merchant'  => '/storage/logos/prodia-tabanan.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'MIRACLE ULTIMATE DENPASAR',
                'kategori'       => 'Kecantikan',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/miracle-ultimate',
                'nama_pic'       => 'Ni Luh Sinta',
                'wa_pic'         => '+6281234567894',
                'daerah'         => 'denpasar',
                'long'           => 115.2100,
                'lat'            => -8.6755,
                'link_gmap'      => 'https://maps.google.com/?q=-8.6755,115.2100',
                'logo_merchant'  => '/storage/logos/miracle-ultimate.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],

            // ================== kupang ==================
            [
                'nama_merchant'  => 'Masterpiece',
                'kategori'       => 'hiburan',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/masterpiece',
                'nama_pic'       => 'Yohanes Maria',
                'wa_pic'         => '+6282234567890',
                'daerah'         => 'kupang',
                'long'           => 123.6070,
                'lat'            => -10.1772,
                'link_gmap'      => 'https://maps.google.com/?q=-10.1772,123.6070',
                'logo_merchant'  => '/storage/logos/masterpiece.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'la Moringa',
                'kategori'       => 'kuliner',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/la-moringa',
                'nama_pic'       => 'Maria Yuliana',
                'wa_pic'         => '+6282234567891',
                'daerah'         => 'kupang',
                'long'           => 123.6080,
                'lat'            => -10.1780,
                'link_gmap'      => 'https://maps.google.com/?q=-10.1780,123.6080',
                'logo_merchant'  => '/storage/logos/la-moringa.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'Nakamura Kupang',
                'kategori'       => 'kecantikan',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/nakamura-kupang',
                'nama_pic'       => 'Stephanie Liufeto',
                'wa_pic'         => '+6282234567892',
                'daerah'         => 'kupang',
                'long'           => 123.6090,
                'lat'            => -10.1790,
                'link_gmap'      => 'https://maps.google.com/?q=-10.1790,123.6090',
                'logo_merchant'  => '/storage/logos/nakamura-kupang.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'Relaxology Kupang',
                'kategori'       => 'kecantikan',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/relaxology-kupang',
                'nama_pic'       => 'Indah Sari',
                'wa_pic'         => '+6282234567893',
                'daerah'         => 'kupang',
                'long'           => 123.6100,
                'lat'            => -10.1800,
                'link_gmap'      => 'https://maps.google.com/?q=-10.1800,123.6100',
                'logo_merchant'  => '/storage/logos/relaxology-kupang.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'Dapur Solokoe',
                'kategori'       => 'kuliner',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/dapur-solokoe',
                'nama_pic'       => 'Yeni Laka',
                'wa_pic'         => '+6282234567894',
                'daerah'         => 'kupang',
                'long'           => 123.6110,
                'lat'            => -10.1810,
                'link_gmap'      => 'https://maps.google.com/?q=-10.1810,123.6110',
                'logo_merchant'  => '/storage/logos/dapur-solokoe.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],

            // ================== mataram ==================
            [
                'nama_merchant'  => 'JELAJAH COFFEE',
                'kategori'       => 'kuliner',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/jelajah-coffee',
                'nama_pic'       => 'Ahmad Rizki',
                'wa_pic'         => '+6283234567890',
                'daerah'         => 'mataram',
                'long'           => 116.1167,
                'lat'            => -8.5833,
                'link_gmap'      => 'https://maps.google.com/?q=-8.5833,116.1167',
                'logo_merchant'  => '/storage/logos/jelajah-coffee.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'B CLINIC',
                'kategori'       => 'kecantikan',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/b-clinic',
                'nama_pic'       => 'Nurul Hidayah',
                'wa_pic'         => '+6283234567891',
                'daerah'         => 'mataram',
                'long'           => 116.1170,
                'lat'            => -8.5840,
                'link_gmap'      => 'https://maps.google.com/?q=-8.5840,116.1170',
                'logo_merchant'  => '/storage/logos/b-clinic.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'LOMBOK WILDLIFE PARK',
                'kategori'       => 'liburan',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/lombok-wildlife-park',
                'nama_pic'       => 'Budi Santoso',
                'wa_pic'         => '+6283234567892',
                'daerah'         => 'mataram',
                'long'           => 116.1180,
                'lat'            => -8.5850,
                'link_gmap'      => 'https://maps.google.com/?q=-8.5850,116.1180',
                'logo_merchant'  => '/storage/logos/lombok-wildlife-park.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'DAPUR SAYUR',
                'kategori'       => 'kuliner',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/dapur-sayur',
                'nama_pic'       => 'Lina Sari',
                'wa_pic'         => '+6283234567893',
                'daerah'         => 'mataram',
                'long'           => 116.1190,
                'lat'            => -8.5860,
                'link_gmap'      => 'https://maps.google.com/?q=-8.5860,116.1190',
                'logo_merchant'  => '/storage/logos/dapur-sayur.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'SALOME HAIR & BEAUTY',
                'kategori'       => 'kecantikan',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/salome-hair-beauty',
                'nama_pic'       => 'Ratna Dewi',
                'wa_pic'         => '+6283234567894',
                'daerah'         => 'mataram',
                'long'           => 116.1200,
                'lat'            => -8.5870,
                'link_gmap'      => 'https://maps.google.com/?q=-8.5870,116.1200',
                'logo_merchant'  => '/storage/logos/salome-hair-beauty.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],

            // ================== flores ==================
            [
                'nama_merchant'  => 'KOPI DENG SAPA',
                'kategori'       => 'kuliner',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/kopi-deng-sapa',
                'nama_pic'       => 'Yohana Bunga',
                'wa_pic'         => '+6284234567890',
                'daerah'         => 'flores',
                'long'           => 122.2121,
                'lat'            => -8.6199,
                'link_gmap'      => 'https://maps.google.com/?q=-8.6199,122.2121',
                'logo_merchant'  => '/storage/logos/kopi-deng-sapa.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'CAFE HM CAFE & RESTO',
                'kategori'       => 'kuliner',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/cafe-hm',
                'nama_pic'       => 'Maria Goreti',
                'wa_pic'         => '+6284234567891',
                'daerah'         => 'flores',
                'long'           => 122.2130,
                'lat'            => -8.6200,
                'link_gmap'      => 'https://maps.google.com/?q=-8.6200,122.2130',
                'logo_merchant'  => '/storage/logos/cafe-hm.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'SIBAKLOANG GALLERY COFFE',
                'kategori'       => 'kuliner',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/sibakloang-gallery',
                'nama_pic'       => 'Yosef Wua',
                'wa_pic'         => '+6284234567892',
                'daerah'         => 'flores',
                'long'           => 122.2140,
                'lat'            => -8.6210,
                'link_gmap'      => 'https://maps.google.com/?q=-8.6210,122.2140',
                'logo_merchant'  => '/storage/logos/sibakloang-gallery.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'CAFE TERAS LANGIT',
                'kategori'       => 'kuliner',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/cafe-teras-langit',
                'nama_pic'       => 'Marta Yeni',
                'wa_pic'         => '+6284234567893',
                'daerah'         => 'flores',
                'long'           => 122.2150,
                'lat'            => -8.6220,
                'link_gmap'      => 'https://maps.google.com/?q=-8.6220,122.2150',
                'logo_merchant'  => '/storage/logos/cafe-teras-langit.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'nama_merchant'  => 'APOTIK TIARA FARM',
                'kategori'       => 'kecantikan',
                'link_blanjapoin' => 'https://blanjapoin.id/merchant/apotik-tiara-farm',
                'nama_pic'       => 'Fransiska Leni',
                'wa_pic'         => '+6284234567894',
                'daerah'         => 'flores',
                'long'           => 122.2160,
                'lat'            => -8.6230,
                'link_gmap'      => 'https://maps.google.com/?q=-8.6230,122.2160',
                'logo_merchant'  => '/storage/logos/apotik-tiara-farm.png',
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
        ];
        foreach ($merchants as &$m) {
            unset($m['long'], $m['lat']);
        }
        unset($m);

        DB::table('merchants')->insert($merchants);
    }
}
